[package]
name = "rustsat"
version = "0.1.0"
edition = "2021"
authors = ["Christoph Jabs <christoph.jabs@helsinki.fi>"]

build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
bzip2 = { version = "0.4", optional = true }
flate2 = { version = "1.0", optional = true }

[features]
default = ["ipasir", "cadical", "optimization"]
ipasir = []
cadical = []
optimization = []
compression = ["dep:bzip2", "dep:flate2"]
