name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --features=all-non-conflicting
    - name: Check formatting
      uses: actions-rust-lang/rustfmt@v1.0.1
    - name: Run tests
      run: cargo test --verbose --features=all-non-conflicting
